Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end
  config.vm.boot_timeout = 60
  config.vbguest.auto_update = false

  config.vm.define "base" do |base|
    base.ssh.username = "vagrant"
    base.vm.host_name = "base.local"
    base.vm.box = "ubuntu/xenial64"
    base.vm.box_version = "20180224.0.0"
    base.vm.provision :shell, :path => "vagrant-bootstrap-base.sh"
    base.vm.network "private_network", ip: "192.168.56.10"
  end

  config.vm.define "zipi" do |zipi|
    zipi.ssh.username = "vagrant"
    zipi.vm.host_name = "zipi.local"
    zipi.vm.box = "ubuntu/xenial64"
    zipi.vm.provision :shell, :path => "vagrant-bootstrap-zipi.sh"
    zipi.vm.network "private_network", ip: "192.168.56.11"
    zipi.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "192.168.56.11", auto_correct: true
  end

  config.vm.define "zape" do |zape|
    zape.ssh.username = "vagrant"
    zape.vm.host_name = "zape.local"
    zape.vm.box = "ubuntu/xenial64"
    zape.vm.provision :shell, :path => "vagrant-bootstrap-zape.sh"
    zape.vm.network "private_network", ip: "192.168.56.12"
  end

  config.vm.define "pantuflo" do |pantuflo|
    pantuflo.ssh.username = "vagrant"
    pantuflo.vm.host_name = "pantuflo.local"
    pantuflo.vm.box = "ubuntu/xenial64"
    pantuflo.vm.network :private_network, ip: '192.168.56.13'
    pantuflo.vm.network "forwarded_port", guest: 9000, host: 9000, host_ip: "192.168.56.13", auto_correct: true
    pantuflo.vm.provider :virtualbox do |vb|
      vb.linked_clone = true
      vb.memory = 2048
      vb.cpus = 2
      vb.customize ['modifyvm', :id, '--cableconnected1', 'on']
    end
    pantuflo.vm.provision :shell, path: 'vagrant-bootstrap-pantuflo.sh'
  end
end
